version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "${WEB_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BASE_PATH=${NEXT_PUBLIC_BASE_PATH:-/supichat}
      - NEXT_PUBLIC_SIGNALING_PATH=${NEXT_PUBLIC_SIGNALING_PATH:-/supichat/socket.io}
      - DEEPL_API_KEY=${DEEPL_API_KEY}
    restart: unless-stopped
    user: "1001:1001"
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true

  signaling:
    build:
      context: .
      dockerfile: Dockerfile.signaling
    ports:
      - "${SIGNALING_PORT:-4001}:4001"
    environment:
      - NODE_ENV=production
      - SIGNALING_PATH=${NEXT_PUBLIC_SIGNALING_PATH:-/supichat/socket.io}
    restart: unless-stopped
    user: "1001:1001"
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/supichat:/etc/ssl/supichat:ro
      - /var/www/certbot:/var/www/certbot:ro
    depends_on:
      - web
      - signaling
    restart: unless-stopped
